services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/ComfyUI/models/
      - ./output:/app/output
      - ./settings:/app/ComfyUI/user/default:rw
      - ./flows:/app/ComfyUI/user/default/workflows:rw
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    tty: true
    restart: unless-stopped
